# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.line_name = QtWidgets.QLineEdit(self.groupBox)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 0, 0, 1, 1)
        self.line_ip_port = QtWidgets.QLineEdit(self.groupBox)
        self.line_ip_port.setObjectName("line_ip_port")
        self.gridLayout.addWidget(self.line_ip_port, 1, 0, 1, 1)
        self.button_connect = QtWidgets.QPushButton(self.groupBox)
        self.button_connect.setObjectName("button_connect")
        self.gridLayout.addWidget(self.button_connect, 1, 1, 1, 1)
        self.status = QtWidgets.QLabel(self.groupBox)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chat = QtWidgets.QTextBrowser(self.groupBox_2)
        self.chat.setObjectName("chat")
        self.gridLayout_2.addWidget(self.chat, 0, 0, 1, 2)
        self.line_message = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_message.setObjectName("line_message")
        self.gridLayout_2.addWidget(self.line_message, 1, 0, 1, 1)
        self.button_send = QtWidgets.QPushButton(self.groupBox_2)
        self.button_send.setObjectName("button_send")
        self.gridLayout_2.addWidget(self.button_send, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection settings"))
        self.line_name.setPlaceholderText(_translate("MainWindow", "Your name"))
        self.line_ip_port.setPlaceholderText(_translate("MainWindow", "ip:port"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.status.setText(_translate("MainWindow", "Disconnected"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chatting"))
        self.line_message.setPlaceholderText(_translate("MainWindow", "Message"))
        self.button_send.setText(_translate("MainWindow", "Send"))
